version: '3.4'

services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile

  authorization.api:
    image: ${DOCKER_REGISTRY-}authorizationapi
    build:
      context: .
      dockerfile: Services/Authorization/Authorization.Api/Dockerfile


  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile


  communication.api:
    image: ${DOCKER_REGISTRY-}communicationapi
    build:
      context: .
      dockerfile: Services/Communication/Communication.Api/Dockerfile


  document.api:
    image: ${DOCKER_REGISTRY-}documentapi
    build:
      context: .
      dockerfile: Services/Document/Document.Api/Dockerfile


  order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: Services/Order/Order.Api/Dockerfile

