version: '3.4'

services:
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: Services
      dockerfile: Basket.Api/Presentation/Dockerfile

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: Services
      dockerfile: Catalog.Api/Presentation/Dockerfile

  authorization.api:
    image: ${DOCKER_REGISTRY-}authorizationapi
    build:
      context: .
      dockerfile: Services/Authorization.Api/Presentation/Dockerfile


  communication.api:
    image: ${DOCKER_REGISTRY-}communicationapi
    build:
      context: .
      dockerfile: Services/Communication.Api/Dockerfile


  document.api:
    image: ${DOCKER_REGISTRY-}documentapi
    build:
      context: .
      dockerfile: Services/Document.Api/Dockerfile


  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering.Api/Dockerfile

  authorization.sqlserver:
    image: mcr.microsoft.com/mssql/server

  catalogdb.mongodb:
    image: mongo

  basketdb.redis:
    image: redis:alpine

volumes:
  mssql_auth:
  mongo_data:




