apiVersion: v1
kind: Service
metadata:
  name: authorization-service
  namespace: rentharbor
  labels:
    app: authorization
spec:
  selector:
    app: authorization-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80