apiVersion: v1
kind: ConfigMap
metadata:
  name: authorization-api-config
  namespace: rentharbor
data:
  appsettings.json: |
    {
      "ConnectionStrings": {
        "PsqlConnectionString": "Server=orderdb.postgres;Port=5432;Database=orderdb;User Id=admin;Password=admin;",
        "MongoDBConnection": "mongodb://catalogdb.mongodb:27017"
      },
      "MongoDBSettings": {
        "DatabaseName": "CatalogDb",
        "CollectionName": "Properties"
      },
      "Logging": {
        "LogLevel": {
          "Default": "Debug",
          "Microsoft": "Information",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "AllowedHosts": "*"
    }
