apiVersion: v1
kind: Service
metadata:
  name: document-service
  namespace: rentharbor
  labels:
    app: document
spec:
  selector:
    app: document-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
