apiVersion: v1
kind: Service
metadata:
  name: communication-service
  namespace: rentharbor
  labels:
    app: communication
spec:
  selector:
    app: communication-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
