apiVersion: v1
kind: ConfigMap
metadata:
  name: basket-api-config
  namespace: rentharbor
data:
  appsettings.json: |
    {
      "ConnectionStrings": {
        "MongoDBConnection": "mongodb://catalogdb.mongodb:27017"
      },
      "MongoDBSettings": {
        "DatabaseName": "CatalogDb",
        "CollectionName": "Properties"
      },
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "AllowedHosts": "*"
    }
