apiVersion: v1
kind: Service
metadata:
  name: basket-service
  namespace: rentharbor
  labels:
    app: basket
spec:
  selector:
    app: basket-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
