apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rentharbor
  name: catalog-api
  labels:
    app: catalog-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
      - name: catalog-api
        image: catalogapi:dev
        ports:
        - containerPort: 80
        command: ["tail", "-f", "/dev/null"]
        volumeMounts:
        - name: config-volume
          mountPath: /app/appsettings.json
          subPath: appsettings.json
      volumes:
      - name: config-volume
        configMap:
          name: catalog-api-config
