apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: rentharbor
  labels:
    app: catalog
spec:
  selector:
    app: catalog-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
